// utils/medPlants.ts
export const plants = [
  {
    slug: 'kamille',
    title: 'Kamille',
    botanicalTitle: 'Matricaria chamomilla',
    image: 'kamille.jpg',
    type: ['Blüte'],
    effectArea: ['entzündungshemmend', 'krampflösend', 'beruhigend', 'antiseptisch'],
    teaser: "Kamille ist eine zarte, weiß-gelbe Blütenpflanze mit markantem Duft. Sie wächst wild auf Wiesen und ist eine der bekanntesten Heilpflanzen Europas.",
    history: "Kamille wurde bereits im alten Ägypten, im antiken Griechenland und Rom für Heilzwecke genutzt. Sie galt dort als Allheilmittel gegen zahlreiche Leiden und wurde höchst geschätzt. Im Laufe der Jahrhunderte entwickelte sie sich zu einer festen Größe in der europäischen Volksmedizin, insbesondere als sanfte Pflanze für die Behandlung von Entzündungen und Hautleiden. Ihre vielfältigen Anwendungsmöglichkeiten sorgen bis heute für ihren hohen Stellenwert.",
    medApplication: "Kamille eignet sich ideal zur Linderung von Magen-Darm-Beschwerden, wirkt krampflösend und beruhigend. Sie ist entzündungshemmend bei Hautreizungen und Erkrankungen der Schleimhäute. Anwendungen erfolgen als Tee, Inhalation, Bäder oder als Umschlag bei kleinen Verletzungen. Ihre antiseptischen Eigenschaften machen sie zudem zu einem bewährten Hausmittel bei leichten Wunden.",
    tasteSmell: "Mild, leicht süßlich mit einem frischen, blumigen und etwas krautigen Aroma. Der typische Kamillenduft ist warm und beruhigend.",
    preparationMethods: ['Tee', 'Inhalation', 'Umschlag', 'Bad', 'Tinktur'],
    combinations: ['pfefferminze', 'melisse', 'lavendel'],
    ingredients: [
      'Ätherische Öle (z.B. Chamazulen)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe',
      'Mineralstoffe (Kalzium, Magnesium)'
    ],
    harvestMonths: [5, 6, 7],
    locations: ['Wiesen', 'Wegränder', 'sonnige Feldränder', 'magere Böden'],
    notesRisks: "Kann bei empfindlichen Personen allergische Reaktionen auslösen, insbesondere bei Allergien gegen Korbblütler. Nicht überdosieren, Schwangere sollten Rücksprache halten.",
    ads: []
  },
  {
    slug: 'lavendel',
    title: 'Lavendel',
    botanicalTitle: 'Lavandula angustifolia',
    image: 'lavendel.jpg',
    type: ['Blüte'],
    effectArea: ['entspannend', 'antiseptisch', 'stimmungsaufhellend', 'schlaffördernd'],
    teaser: "Lavendel zeigt sich mit violetten Blütenähren und starkem Duft. Er wächst vor allem im Mittelmeerraum und spielt auch in Gärten eine wichtige Rolle.",
    history: "Bereits im antiken Rom und Griechenland wurde Lavendel als Badezusatz und Duftspender geschätzt. Mittelalterliche Klostergärten brachten die Pflanze nach Mitteleuropa, wo sie zur Reinigung, Beruhigung und Desinfektion diente. Bis heute ist Lavendel als Heil- und Duftpflanze beliebt. Besonders wegen seiner entspannenden Wirkung auf Nerven und Psyche findet er breite Anwendung in der Naturheilkunde.",
    medApplication: "Lavendel wird vor allem bei innerer Unruhe, Schlafproblemen und Stresssymptomen eingesetzt. Das ätherische Lavendelöl eignet sich für die Aromatherapie, Massage und als Badezusatz. Auch bei Hautreizungen, leichten Verbrennungen oder Insektenstichen kann Lavendel unterstützend wirken. Tees helfen sanft beim Einschlafen und zur allgemeinen Entspannung.",
    tasteSmell: "Kräftig aromatisch, leicht süßlich mit blumigen und harzigen Noten. Der Duft wirkt beruhigend und mediterran-frisch.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Duftsäckchen', 'Tinktur'],
    combinations: ['melisse', 'kamille', 'thymian'],
    ingredients: [
      'Ätherische Öle (Linalool, Linalylacetat)',
      'Gerbstoffe',
      'Flavonoide',
      'Cumarine'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['sonnige Gärten', 'Felder', 'Mittelmeerregion', 'steinige Böden'],
    notesRisks: "Bei Überempfindlichkeit gegen ätherische Öle vorsichtig dosieren. In hohen Dosen kann Lavendel sedierend wirken.",
    ads: []
  },
  {
    slug: 'pfefferminze',
    title: 'Pfefferminze',
    botanicalTitle: 'Mentha × piperita',
    image: 'pfefferminze.jpg',
    type: ['Kraut'],
    effectArea: [
        'appetitanregend',
        'verdauungsfördernd',
        'krampflösend',
        'entzündungshemmend',
        'schmerzlindernd',
        'schleimlösend',
        'erfrischend',
        'durchblutungsfördernd',
        'stressreduzierend',
        'antiseptisch',
        'immunmodulierend'
    ],
    teaser: "Pfefferminze besitzt kräftig-grüne Blätter und einen ausgeprägten, frischen Duft. Sie ist in Europa weit verbreitet und als Würz- und Heilpflanze beliebt.",
    history: "Die Pfefferminze entstand im 17. Jahrhundert als Kreuzung unterschiedlicher Minzarten. Schon bald wurde sie in Europa als Heilmittel gegen Magen-und Darmleiden genutzt. In vielen Kulturen gilt sie traditionell als probates Mittel zur Erfrischung und als Aromageber für Getränke und Speisen. Bis heute ist sie aus der Hausapotheke und Naturheilkunde nicht wegzudenken.",
    medApplication: "Pfefferminze fördert die Verdauung, lindert Krämpfe und hilft bei Kopfschmerzen, Erkältungen oder Übelkeit. Ihr ätherisches Öl hat eine entspannende Wirkung auf die Muskulatur. Als Tee, in Bädern, als Öl oder als Salbe zur äußeren Anwendung ist Pfefferminze vielseitig einsetzbar. Häufig findet sie auch Anwendung bei Konzentrationsstörungen.",
    tasteSmell: "Intensiv frisch, kühlend, mit ausgeprägtem Mentholaroma und leicht süßem Unterton.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Tinktur', 'Sirup'],
    combinations: ['kamille', 'melisse', 'thymian'],
    ingredients: [
      'Ätherische Öle (Menthol, Menthon)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['feuchte Wiesen', 'Gärten', 'halbschattige Standorte'],
    notesRisks: "Nicht bei Säuglingen anwenden, da Menthol Atemprobleme verursachen kann. Bei Gallensteinen Vorsicht geboten.",
    ads: []
  },
    {
    slug: 'melisse',
    title: 'Zitronenmelisse',
    botanicalTitle: 'Melissa officinalis',
    image: 'zitronenmelisse.webp',
    type: ['Kraut'],
    effectArea: ['beruhigend', 'krampflösend', 'antiviral', 'stimmungsaufhellend'],
    teaser: "Die Zitronenmelisse verströmt einen erfrischenden Zitronenduft und ist sowohl in der Küche als auch in der Heilkunde geschätzt.",
    history: "Schon im Mittelalter wurde Melisse in Klostergärten angebaut, um Herz und Gemüt zu stärken. Die Araber führten sie in die europäische Medizin ein, wo sie als Mittel gegen Melancholie und Schlaflosigkeit diente.",
    medApplication: "Melisse wirkt beruhigend bei Nervosität, Schlafproblemen und Magen-Darm-Beschwerden. Äußerlich angewendet kann sie bei Lippenherpes helfen.",
    tasteSmell: "Zitronig-frisch, mild süßlich, leicht herb.",
    preparationMethods: ['Tee', 'Tinktur', 'Bad', 'Öl'],
    combinations: ['kamille', 'lavendel', 'pfefferminze'],
    ingredients: [
      'Ätherische Öle (Citral, Citronellal)',
      'Rosmarinsäure',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Gärten', 'Kräuterbeete', 'sonnig bis halbschattig'],
    notesRisks: "In hohen Dosen kann es zu Schläfrigkeit kommen. Nicht während einer Schilddrüsenunterfunktion ohne ärztlichen Rat anwenden.",
    ads: []
  },
  {
    slug: 'thymian',
    title: 'Thymian',
    botanicalTitle: 'Thymus vulgaris',
    image: 'thymian.jpg',
    type: ['Kraut'],
    effectArea: ['antibakteriell', 'schleimlösend', 'entzündungshemmend', 'krampflösend'],
    teaser: "Thymian ist eine mediterrane Gewürz- und Heilpflanze mit intensivem Aroma und kleinen lila Blüten.",
    history: "Bereits die alten Ägypter nutzten Thymian zum Einbalsamieren, Römer schätzten ihn als Würzkraut und Heilpflanze. Im Mittelalter wurde er gegen Atemwegsbeschwerden eingesetzt.",
    medApplication: "Thymian lindert Husten und Bronchitis, fördert die Schleimlösung und wirkt desinfizierend im Mund- und Rachenraum.",
    tasteSmell: "Würzig, leicht pfeffrig, intensiv aromatisch mit harziger Note.",
    preparationMethods: ['Tee', 'Sirup', 'Öl', 'Inhalation'],
    combinations: ['salbei', 'pfefferminze', 'lavendel'],
    ingredients: [
      'Ätherische Öle (Thymol, Carvacrol)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Kräuterbeete', 'Felsige Böden', 'sonnig'],
    notesRisks: "Nicht in zu hoher Dosierung bei empfindlichem Magen. Ätherisches Öl kann Haut reizen.",
    ads: []
  },
  {
    slug: 'salbei',
    title: 'Salbei',
    botanicalTitle: 'Salvia officinalis',
    image: 'salbei.jpg',
    type: ['Kraut'],
    effectArea: ['antibakteriell', 'entzündungshemmend', 'schweißhemmend', 'verdauungsfördernd'],
    teaser: "Salbei hat längliche, filzig behaarte aromatische Blätter. Die Pflanze wächst buschig und gedeiht sowohl wild als auch in Gärten.",
    history: "Salbei war bereits den Römern und Griechen als kostbares Heilkraut bekannt. Im Mittelalter wurde er zur „Königin der Heilpflanzen“ ernannt und war ein wichtiger Bestandteil der Klostermedizin. Salbei galt insbesondere als Mittel gegen Halsschmerzen und Entzündungen. In der Volksmedizin wurde er zudem als universelle Arznei und Würzkraut geschätzt.",
    medApplication: "Salbei wird als Tee oder Gurgellösung bei Halsentzündungen und Entzündungen der Mundschleimhaut verwendet. Seine antibakterielle Wirkung macht ihn zu einem bewährten Heilmittel bei Infekten. Außerdem ist Salbei hilfreich bei übermäßigem Schwitzen und kann äußerlich zur Wundheilung sowie als Badezusatz eingesetzt werden.",
    tasteSmell: "Herb, würzig, leicht bitter mit kampferartiger Note.",
    preparationMethods: ['Tee', 'Gurgellösung', 'Tinktur', 'Öl'],
    combinations: ['thymian', 'kamille', 'rosmarin'],
    ingredients: [
      'Ätherische Öle (Thujon, Cineol)',
      'Gerbstoffe',
      'Flavonoide',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Kräuterbeete', 'Steinige Böden', 'sonnig'],
    notesRisks: "Nicht in großen Mengen in der Schwangerschaft. Längere Anwendung von reinem Öl vermeiden.",
    ads: []
  },
  {
    slug: 'rosmarin',
    title: 'Rosmarin',
    botanicalTitle: 'Rosmarinus officinalis',
    image: 'rosmarin.jpg',
    type: ['Kraut'],
    effectArea: ['durchblutungsfördernd', 'verdauungsfördernd', 'belebend', 'antioxidativ'],
    teaser: "Rosmarin ist ein immergrüner Halbstrauch mit kräftigem Aroma, der aus dem Mittelmeerraum stammt.",
    history: "Schon die Griechen und Römer nutzten Rosmarin als Gedächtnisstütze und Schutzpflanze. In der Küche und Medizin gleichermaßen beliebt.",
    medApplication: "Wirkt anregend, fördert die Verdauung und lindert Muskelschmerzen. Äußerlich als Badezusatz belebend.",
    tasteSmell: "Kräftig harzig, leicht kampferartig, würzig.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Tinktur'],
    combinations: ['salbei', 'thymian', 'lavendel'],
    ingredients: [
      'Ätherische Öle (1,8-Cineol, Campher)',
      'Bitterstoffe',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [5, 6, 7],
    locations: ['sonnige Kräuterbeete', 'trockene Böden', 'Mittelmeerregion'],
    notesRisks: "Nicht bei Bluthochdruck oder in der Schwangerschaft in großen Mengen verwenden.",
    ads: []
  },
  {
    slug: 'brennnessel',
    title: 'Brennnessel',
    botanicalTitle: 'Urtica dioica',
    image: 'brennnessel.jpg',
    type: ['Kraut'],
    effectArea: ['stoffwechselanregend', 'entwässernd', 'entzündungshemmend', 'blutreinigend'],
    teaser: "Die Brennnessel ist eine kraftvolle Heilpflanze, die oft unterschätzt wird.",
    history: "Seit Jahrhunderten als Gemüse, Faserpflanze und Heilmittel geschätzt. In Kriegszeiten war sie wichtige Nahrungsquelle.",
    medApplication: "Wirkt harntreibend, regt den Stoffwechsel an, lindert Gelenkschmerzen und unterstützt bei Hautproblemen.",
    tasteSmell: "Spinatähnlich, leicht nussig, grün-aromatisch.",
    preparationMethods: ['Tee', 'Gemüse', 'Tinktur'],
    combinations: ['schachtelhalm', 'löwenzahn', 'petersilie'],
    ingredients: [
      'Mineralstoffe (Eisen, Kalzium, Magnesium, Kalium)',
      'Vitamine (A, C, K)',
      'Flavonoide',
      'Chlorophyll',
      'Kieselsäure'
    ],
    harvestMonths: [4, 5, 6],
    locations: ['Wegränder', 'Wiesen', 'nährstoffreiche Böden'],
    notesRisks: "Frische Pflanze kann Hautreizungen verursachen. Nicht bei Herz- oder Nierenproblemen in großen Mengen verzehren.",
    ads: []
  },
  {
    slug: 'schafgarbe',
    title: 'Schafgarbe',
    botanicalTitle: 'Achillea millefolium',
    image: 'schafgarbe.jpg',
    type: ['Kraut', 'Blüte'],
    effectArea: ['krampflösend', 'entzündungshemmend', 'blutstillend', 'verdauungsfördernd'],
    teaser: "Schafgarbe mit ihren gefiederten Blättern und weißen Blüten ist ein bewährtes Heilkraut.",
    history: "Schon in der Antike bekannt, wird sie seit Jahrhunderten gegen Verdauungsbeschwerden und Wunden eingesetzt.",
    medApplication: "Hilft bei Magen-Darm-Krämpfen, reguliert den Menstruationszyklus und unterstützt die Wundheilung.",
    tasteSmell: "Herb, leicht bitter, aromatisch.",
    preparationMethods: ['Tee', 'Tinktur', 'Bad'],
    combinations: ['kamille', 'pfefferminze', 'melisse'],
    ingredients: [
      'Ätherische Öle (Chamazulen, Cineol)',
      'Bitterstoffe',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Wiesen', 'Wegränder', 'sonnige Hänge'],
    notesRisks: "Kann Hautreizungen verursachen. Nicht in der Schwangerschaft anwenden.",
    ads: []
  },
  {
    slug: 'ringelblume',
    title: 'Ringelblume',
    botanicalTitle: 'Calendula officinalis',
    image: 'ringelblume.jpg',
    type: ['Blüte'],
    effectArea: ['entzündungshemmend', 'wundheilend', 'antibakteriell', 'hautpflegend'],
    teaser: "Leuchtend orange Blüten machen die Ringelblume zu einem Blickfang im Garten.",
    history: "Seit dem Mittelalter bekannt als Heil- und Zierpflanze. Vor allem in Salben und Tees verwendet.",
    medApplication: "Fördert die Wundheilung, lindert Hautreizungen und wirkt entzündungshemmend.",
    tasteSmell: "Mild, leicht würzig, blumig.",
    preparationMethods: ['Tee', 'Salbe', 'Tinktur'],
    combinations: ['kamille', 'schafgarbe', 'lavendel'],
    ingredients: [
      'Flavonoide',
      'Carotinoide',
      'Saponine',
      'Ätherische Öle'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Gärten', 'Beete', 'sonnig'],
    notesRisks: "Kann bei Allergien gegen Korbblütler problematisch sein.",
    ads: []
  },
  {
    slug: 'baldrian',
    title: 'Baldrian',
    botanicalTitle: 'Valeriana officinalis',
    image: 'baldrian.jpg',
    type: ['Wurzel'],
    effectArea: ['beruhigend', 'schlaffördernd', 'krampflösend'],
    teaser: "Mit seinen zarten Blüten und der kräftigen Wurzel ist Baldrian ein bewährtes Mittel gegen Unruhe.",
    history: "Seit der Antike geschätzt, besonders in der Klostermedizin als sanftes Beruhigungsmittel verwendet.",
    medApplication: "Hilft bei nervöser Unruhe, Einschlafstörungen und leichten Krämpfen.",
    tasteSmell: "Erdig, aromatisch, leicht bitter mit charakteristischem Geruch.",
    preparationMethods: ['Tee', 'Tinktur', 'Tablette'],
    combinations: ['melisse', 'hopfen', 'passionsblume'],
    ingredients: [
      'Valepotriate',
      'Ätherische Öle',
      'Alkaloide',
      'Flavonoide'
    ],
    harvestMonths: [9, 10],
    locations: ['Feuchtwiesen', 'Waldränder', 'Gärten'],
    notesRisks: "Längere Anwendung kann zu Tagesmüdigkeit führen. Nicht mit Alkohol kombinieren.",
    ads: []
  },
  {
      slug: 'cistus',
      title: 'Cistus',
      botanicalTitle: 'Cistus incanus',
      image: 'cistus.jpg',
      type: ['Blatt'],
      effectArea: ['antiviral', 'antibakteriell', 'antioxidativ', 'entzündungshemmend'],
      teaser: "Cistus, auch Zistrose genannt, ist ein stark duftender Strauch aus dem Mittelmeerraum. In der Naturheilkunde gilt er als Schutzschild gegen Viren und Bakterien.",
      history: "Bereits im antiken Griechenland wurde Cistus als Räucherwerk und Heilpflanze genutzt. In jüngerer Zeit wurde seine antivirale Wirkung wiederentdeckt – besonders bei Erkältungskrankheiten.",
      medApplication: "Cistus wird zur Stärkung des Immunsystems, bei Erkältungen und zur Vorbeugung von Infekten verwendet. Besonders beliebt ist Cistus-Tee. Die Pflanze gilt als stark antioxidativ und entzündungshemmend.",
      tasteSmell: "Herb, leicht bitter, harzig.",
      preparationMethods: ['Tee', 'Tinktur'],
      combinations: ['salbei', 'thymian', 'kamille'],
      ingredients: [
        'Polyphenole',
        'Flavonoide',
        'Ätherische Öle',
        'Gerbstoffe'
      ],
      harvestMonths: [5, 6, 7],
      locations: ['Mittelmeerregion', 'sonnig', 'trockene Hänge'],
      notesRisks: "Kann bei empfindlichem Magen zu leichter Reizung führen.",
      ads: []
  },
  {
      slug: 'frauenmantel',
      title: 'Frauenmantel',
      botanicalTitle: 'Alchemilla vulgaris',
      image: 'frauenmantel.jpg',
      type: ['Blatt'],
      effectArea: ['hormonregulierend', 'krampflösend', 'entzündungshemmend'],
      teaser: "Der Frauenmantel mit seinen weichen, rundlichen Blättern gilt als eine der wichtigsten Heilpflanzen für Frauen. Er wächst auf Wiesen, Waldrändern und Gebirgsregionen.",
  history: "Schon im Mittelalter wurde Frauenmantel als 'Frauenkraut' verehrt. Heilkundige wie Hildegard von Bingen empfahlen ihn zur Stärkung der Gebärmutter und zur Linderung von Menstruationsbeschwerden. In der Volksmedizin hatte er einen festen Platz bei allen Themen rund um den weiblichen Zyklus.",
  medApplication: "Frauenmantel wird vor allem bei Menstruationsbeschwerden, Wechseljahrsbeschwerden und zur Zyklusregulation eingesetzt. Seine krampflösende Wirkung hilft bei Unterleibsschmerzen. Als Tee oder Tinktur kann er unterstützend bei hormonellen Ungleichgewichten wirken.",
tasteSmell: "Mild, leicht herb.",
      preparationMethods: ['Tee', 'Tinktur'],
      combinations: ['schafgarbe', 'kamille', 'melisse'],
      ingredients: [
        'Gerbstoffe',
        'Flavonoide',
        'Bitterstoffe',
        'Saponine'
      ],
      harvestMonths: [5, 6, 7, 8],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: "Keine bekannten Nebenwirkungen bei normaler Dosierung.",
      ads: []
  },
  {
      slug: 'giersch',
      title: 'Giersch',
      botanicalTitle: 'Aegopodium podagraria',
      image: 'giersch.jpg',
      type: ['Blatt'],
      effectArea: ['entwässernd', 'stoffwechselanregend', 'entzündungshemmend'],
      teaser: "Der unterschätzte Gartenbewohner mit großem Heil- und Nährwert.",
      history: "Früher als Heilpflanze gegen Gicht und Rheuma bekannt – daher auch der Name 'Podagraria'.",
      medApplication: "Hilft bei Gelenkbeschwerden, regt den Stoffwechsel an und wirkt leicht harntreibend.",
      tasteSmell: "Frisch, mild, leicht nach Petersilie.",
      preparationMethods: ['Salat', 'Pesto', 'Tee'],
      combinations: ['brennnessel', 'löwenzahn', 'petersilie'],
      ingredients: [
        'Vitamin C',
        'Kalium',
        'Flavonoide',
        'Ätherische Öle'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Gärten', 'Wälder', 'Wegränder'],
      notesRisks: "Kann leicht mit giftigen Doldenblütlern verwechselt werden – sichere Bestimmung nötig.",
      ads: []
  },
  {
      slug: 'ingwer',
      title: 'Ingwer',
      botanicalTitle: 'Zingiber officinale',
      image: 'ingwer.jpg',
      type: ['Wurzel'],
      effectArea: ['entzündungshemmend', 'verdauungsfördernd', 'durchblutungsfördernd', 'immunsystemstärkend'],
      teaser: "Ingwer ist eine tropische Wurzel mit knollenartiger Form und scharf-aromatischem Geschmack. Seine zitronige Schärfe ist charakteristisch.",
      history: "Ingwer wird seit Jahrtausenden vor allem in Asien als Heilmittel bei Verdauungsproblemen, Erkältungen und Entzündungen eingesetzt. Über den Seehandel gelangte er nach Europa, wo er schnell geschätzt wurde. Die vielseitige Wirkung der Ingwerwurzel macht ihn weltweit zu einer der wichtigsten und beliebtesten Gewürz- und Heilpflanzen.",
      medApplication: "Ingwer unterstützt die Verdauung, lindert Übelkeit, wirkt entzündungshemmend und antioxidativ. Er hilft bei Reiseübelkeit, Erkältungen oder Kreislaufproblemen. Frisch, als Tee, Pulver oder Extrakt kommt Ingwer innerlich und äußerlich zum Einsatz.",
      tasteSmell: "Scharf, zitronig, aromatisch.",
      preparationMethods: ['Tee', 'Pulver', 'Frischverwendung', 'Tinktur'],
      combinations: ['zitronengras', 'kurkuma', 'honig'],
      ingredients: [
        'Gingerole',
        'Shogaole',
        'Ätherische Öle',
        'Vitamin C'
      ],
      harvestMonths: [1, 2, 11, 12],
      locations: ['Tropen', 'Gewächshaus', 'Kübelkultur'],
      notesRisks: "Kann Sodbrennen verstärken und Blutgerinnung beeinflussen.",
      ads: []
  },
  {
      slug: 'johanniskraut',
      title: 'Johanniskraut',
      botanicalTitle: 'Hypericum perforatum',
      image: 'johanniskraut.jpg',
      type: ['Blüte'],
      effectArea: ['stimmungsaufhellend', 'antidepressiv', 'entzündungshemmend'],
      teaser: "Johanniskraut ist an seinen leuchtend gelben Blüten und durchscheinenden Blättern zu erkennen – es wächst auf Wiesen und an Wegrändern.",
      history: "Johanniskraut wird seit Jahrhunderten traditionell bei Verstimmungen und zur Wundbehandlung eingesetzt. Seine gelben Blüten gelten als „Sonnenfänger“ und Symbol für Licht und Hoffnung. Die Entdeckung der stimmungsaufhellenden Wirkung trug zu seiner heutigen Bedeutung als pflanzliches Antidepressivum maßgeblich bei. In Volksmedizin und Kräuterheilkunde ist Johanniskraut fest verwurzelt.",
      medApplication: "Johanniskraut hilft natürlich bei leichten bis mittleren Depressionen und nervösem Unwohlsein. Es wird als Tee, Öl oder Extrakt angewendet und ist gut verträglich. Darüber hinaus kommen seine entzündungshemmenden Eigenschaften bei Hautproblemen und leichten Verbrennungen äußerlich zum Einsatz.",
      tasteSmell: "Herb, leicht bitter, aromatisch.",
      preparationMethods: ['Tee', 'Ölauszug', 'Tinktur'],
      combinations: ['melisse', 'baldrian', 'passionsblume'],
      ingredients: [
        'Hypericin',
        'Hyperforin',
        'Flavonoide',
        'Gerbstoffe'
      ],
      harvestMonths: [6, 7, 8],
      locations: ['Wiesen', 'Waldränder', 'sonnige Hänge'],
      notesRisks: "Erhöht die Lichtempfindlichkeit der Haut; kann Wechselwirkungen mit Medikamenten verursachen.",
      ads: []
  },
  {
      slug: 'loewenzahn',
      title: 'Löwenzahn',
      botanicalTitle: 'Taraxacum officinale',
      image: 'loewenzahn.jpg',
      type: ['Blatt', 'Wurzel', 'Blüte'],
      effectArea: ['entwässernd', 'verdauungsfördernd', 'stoffwechselanregend'],
      teaser: "Löwenzahn mit seinen leuchtend gelben Blüten ist ein Symbol des Frühlings. Doch er ist nicht nur schön – seine Heilwirkung ist vielseitig und tiefgehend.",
      history: "Löwenzahn wurde bereits im Altertum als verdauungsförderndes Mittel verwendet. Im Mittelalter galt er als 'Lebenselixier' für Leber und Galle. Seine Nutzung reicht von der Volksmedizin bis zur modernen Phytotherapie.",
      medApplication: "Löwenzahn regt Leber, Galle und Nieren an und unterstützt den Körper bei der Entgiftung. Er wird bei Völlegefühl, Blähungen und Appetitlosigkeit empfohlen. Besonders wirksam sind Tees und Tinkturen aus Wurzel und Blatt.",
      tasteSmell: "Bitter, leicht nussig, frisch.",
      preparationMethods: ['Tee', 'Salat', 'Kaffeeersatz'],
      combinations: ['brennnessel', 'giersch', 'petersilie'],
      ingredients: [
        'Bitterstoffe',
        'Flavonoide',
        'Vitamin C',
        'Kalium'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: "Kann bei Gallensteinen problematisch sein.",
      ads: []
  },
  {
      slug: 'maedesuess',
      title: 'Mädesüß',
      botanicalTitle: 'Filipendula ulmaria',
      image: 'maedesuess.webp',
      type: ['Blüte'],
      effectArea: ['schmerzstillend', 'entzündungshemmend', 'fiebersenkend'],
      teaser: "Mädesüß mit seinen cremig-weißen Blüten verströmt einen süßlichen Duft. Es wächst an Bachufern und in feuchten Wiesen – ein echter Naturheiler.",
      history: "Mädesüß enthält natürliche Salicylate – Vorläufer des Aspirins. Schon in der Antike und später in der Klostermedizin wurde es zur Fiebersenkung und Schmerzlinderung genutzt.",
      medApplication: "Mädesüß hilft bei Erkältungen, Fieber und leichten Schmerzen. Es wirkt ähnlich wie Aspirin, aber sanfter. Verwendet werden vor allem Blüten und Blätter als Tee oder Tinktur.",
      tasteSmell: "Süßlich, mandelartig, aromatisch.",
      preparationMethods: ['Tee', 'Tinktur', 'Sirup'],
      combinations: ['weidenrinde', 'lindenblüte', 'holunder'],
      ingredients: [
        'Salicylsäureverbindungen',
        'Flavonoide',
        'Gerbstoffe',
        'Ätherische Öle'
      ],
      harvestMonths: [6, 7, 8],
      locations: ['Feuchtwiesen', 'Bachufer', 'Gräben'],
      notesRisks: "Nicht bei Salicylat-Allergie oder Magengeschwüren anwenden.",
      ads: []
  },
  {
      slug: 'spitzwegerich',
      title: 'Spitzwegerich',
      botanicalTitle: 'Plantago lanceolata',
      image: 'spitzwegerich.jpg',
      type: ['Blatt'],
      effectArea: ['hustenstillend', 'entzündungshemmend', 'wundheilend'],
      teaser: "Spitzwegerich ist eine robuste Pflanze mit langen, schmalen Blättern. Er wächst oft unbeachtet an Wegrändern – dabei steckt in ihm eine wahre Heilkraft.",
      history: "Bereits in der Antike war Spitzwegerich bekannt. Die Germanen und später die Klostermedizin nutzten ihn zur Behandlung von Husten, Insektenstichen und Hautverletzungen. Besonders beliebt war er wegen seiner reizlindernden Schleimstoffe.",
      medApplication: "Spitzwegerich lindert Hustenreiz, unterstützt die Schleimlösung und wirkt bei Reizungen der Atemwege. Als Tee, Sirup oder Tinktur wird er vor allem bei Bronchitis und Reizhusten verwendet. Äußerlich hilft er bei kleinen Wunden und Insektenstichen.",
      tasteSmell: "Mild, leicht herb, grasig.",
      preparationMethods: ['Tee', 'Sirup', 'Frischsaft'],
      combinations: ['thymian', 'kamille', 'islandmoos'],
      ingredients: [
        'Schleimstoffe',
        'Gerbstoffe',
        'Aucubin',
        'Flavonoide'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: "Keine bekannten Nebenwirkungen bei normaler Anwendung.",
      ads: []
  },
  {
      slug: 'vogelmiere',
      title: 'Vogelmiere',
      botanicalTitle: 'Stellaria media',
      image: 'vogelmiere.jpg',
      type: ['Blatt', 'Stängel', 'Blüte'],
      effectArea: ['hautheilend', 'entzündungshemmend', 'stoffwechselanregend'],
      teaser: "Vogelmiere ist eine zarte, bodennahe Pflanze mit kleinen weißen Blüten. Sie wächst das ganze Jahr über – oft übersehen, aber voller Kraft.",
      history: "Seit Jahrhunderten wird Vogelmiere in der Volksmedizin verwendet – vor allem zur Hautpflege und bei Ekzemen. Ihre milden Eigenschaften machten sie besonders bei empfindlicher Haut beliebt.",
      medApplication: "Vogelmiere wirkt kühlend und juckreizstillend bei Hautproblemen wie Ekzemen oder Insektenstichen. Sie wird frisch als Auflage, in Salben oder als Tee bei Stoffwechselstörungen verwendet.",
      tasteSmell: "Mild, frisch, leicht süßlich.",
      preparationMethods: ['Salat', 'Smoothie', 'Tee'],
      combinations: ['giersch', 'brennnessel', 'löwenzahn'],
      ingredients: [
        'Vitamin C',
        'Saponine',
        'Mineralstoffe',
        'Flavonoide'
      ],
      harvestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
      locations: ['Gärten', 'Wiesen', 'Beete'],
      notesRisks: "Kann bei übermäßigem Verzehr leicht abführend wirken.",
      ads: []
  }



]
