// utils/medPlants.ts
export const plants = [
  {
    slug: 'kamille',
    title: 'Kamille',
    botanicalTitle: 'Matricaria chamomilla',
    image: 'kamille.jpg',
    type: ['Blüte'],
    effectArea: ['entzündungshemmend', 'krampflösend', 'beruhigend', 'antiseptisch'],
    teaser: "Kamille ist eine zarte, weiß-gelbe Blütenpflanze mit markantem Duft. Sie wächst wild auf Wiesen und ist eine der bekanntesten Heilpflanzen Europas.",
    history: "Kamille wurde bereits im alten Ägypten, im antiken Griechenland und Rom für Heilzwecke genutzt. Sie galt dort als Allheilmittel gegen zahlreiche Leiden und wurde höchst geschätzt. Im Laufe der Jahrhunderte entwickelte sie sich zu einer festen Größe in der europäischen Volksmedizin, insbesondere als sanfte Pflanze für die Behandlung von Entzündungen und Hautleiden. Ihre vielfältigen Anwendungsmöglichkeiten sorgen bis heute für ihren hohen Stellenwert.",
    medApplication: "Kamille eignet sich ideal zur Linderung von Magen-Darm-Beschwerden, wirkt krampflösend und beruhigend. Sie ist entzündungshemmend bei Hautreizungen und Erkrankungen der Schleimhäute. Anwendungen erfolgen als Tee, Inhalation, Bäder oder als Umschlag bei kleinen Verletzungen. Ihre antiseptischen Eigenschaften machen sie zudem zu einem bewährten Hausmittel bei leichten Wunden.",
    tasteSmell: "Mild, leicht süßlich mit einem frischen, blumigen und etwas krautigen Aroma. Der typische Kamillenduft ist warm und beruhigend.",
    preparationMethods: ['Tee', 'Inhalation', 'Umschlag', 'Bad', 'Tinktur'],
    combinations: ['pfefferminze', 'melisse', 'lavendel'],
    ingredients: [
      'Ätherische Öle (z.B. Chamazulen)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe',
      'Mineralstoffe (Kalzium, Magnesium)'
    ],
    harvestMonths: [5, 6, 7],
    locations: ['Wiesen', 'Wegränder', 'sonnige Feldränder', 'magere Böden'],
    notesRisks: "Kann bei empfindlichen Personen allergische Reaktionen auslösen, insbesondere bei Allergien gegen Korbblütler. Nicht überdosieren, Schwangere sollten Rücksprache halten.",
    ads: []
  },
  {
    slug: 'lavendel',
    title: 'Lavendel',
    botanicalTitle: 'Lavandula angustifolia',
    image: 'lavendel.jpg',
    type: ['Blüte'],
    effectArea: ['entspannend', 'antiseptisch', 'stimmungsaufhellend', 'schlaffördernd'],
    teaser: "Lavendel zeigt sich mit violetten Blütenähren und starkem Duft. Er wächst vor allem im Mittelmeerraum und spielt auch in Gärten eine wichtige Rolle.",
    history: "Bereits im antiken Rom und Griechenland wurde Lavendel als Badezusatz und Duftspender geschätzt. Mittelalterliche Klostergärten brachten die Pflanze nach Mitteleuropa, wo sie zur Reinigung, Beruhigung und Desinfektion diente. Bis heute ist Lavendel als Heil- und Duftpflanze beliebt. Besonders wegen seiner entspannenden Wirkung auf Nerven und Psyche findet er breite Anwendung in der Naturheilkunde.",
    medApplication: "Lavendel wird vor allem bei innerer Unruhe, Schlafproblemen und Stresssymptomen eingesetzt. Das ätherische Lavendelöl eignet sich für die Aromatherapie, Massage und als Badezusatz. Auch bei Hautreizungen, leichten Verbrennungen oder Insektenstichen kann Lavendel unterstützend wirken. Tees helfen sanft beim Einschlafen und zur allgemeinen Entspannung.",
    tasteSmell: "Kräftig aromatisch, leicht süßlich mit blumigen und harzigen Noten. Der Duft wirkt beruhigend und mediterran-frisch.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Duftsäckchen', 'Tinktur'],
    combinations: ['melisse', 'kamille', 'thymian'],
    ingredients: [
      'Ätherische Öle (Linalool, Linalylacetat)',
      'Gerbstoffe',
      'Flavonoide',
      'Cumarine'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['sonnige Gärten', 'Felder', 'Mittelmeerregion', 'steinige Böden'],
    notesRisks: "Bei Überempfindlichkeit gegen ätherische Öle vorsichtig dosieren. In hohen Dosen kann Lavendel sedierend wirken.",
    ads: []
  },
  {
    slug: 'pfefferminze',
    title: 'Pfefferminze',
    botanicalTitle: 'Mentha × piperita',
    image: 'pfefferminze.jpg',
    type: ['Kraut'],
    effectArea: [
        'appetitanregend',
        'verdauungsfördernd',
        'krampflösend',
        'entzündungshemmend',
        'schmerzlindernd',
        'schleimlösend',
        'erfrischend',
        'durchblutungsfördernd',
        'stressreduzierend',
        'antiseptisch',
        'immunmodulierend'
    ],
    teaser: "Pfefferminze besitzt kräftig-grüne Blätter und einen ausgeprägten, frischen Duft. Sie ist in Europa weit verbreitet und als Würz- und Heilpflanze beliebt.",
    history: "Die Pfefferminze entstand im 17. Jahrhundert als Kreuzung unterschiedlicher Minzarten. Schon bald wurde sie in Europa als Heilmittel gegen Magen-und Darmleiden genutzt. In vielen Kulturen gilt sie traditionell als probates Mittel zur Erfrischung und als Aromageber für Getränke und Speisen. Bis heute ist sie aus der Hausapotheke und Naturheilkunde nicht wegzudenken.",
    medApplication: "Pfefferminze fördert die Verdauung, lindert Krämpfe und hilft bei Kopfschmerzen, Erkältungen oder Übelkeit. Ihr ätherisches Öl hat eine entspannende Wirkung auf die Muskulatur. Als Tee, in Bädern, als Öl oder als Salbe zur äußeren Anwendung ist Pfefferminze vielseitig einsetzbar. Häufig findet sie auch Anwendung bei Konzentrationsstörungen.",
    tasteSmell: "Intensiv frisch, kühlend, mit ausgeprägtem Mentholaroma und leicht süßem Unterton.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Tinktur', 'Sirup'],
    combinations: ['kamille', 'melisse', 'thymian'],
    ingredients: [
      'Ätherische Öle (Menthol, Menthon)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['feuchte Wiesen', 'Gärten', 'halbschattige Standorte'],
    notesRisks: "Nicht bei Säuglingen anwenden, da Menthol Atemprobleme verursachen kann. Bei Gallensteinen Vorsicht geboten.",
    ads: []
  },
    {
    slug: 'melisse',
    title: 'Zitronenmelisse',
    botanicalTitle: 'Melissa officinalis',
    image: 'zitronenmelisse.webp',
    type: ['Kraut'],
    effectArea: ['beruhigend', 'krampflösend', 'antiviral', 'stimmungsaufhellend'],
    teaser: "Die Zitronenmelisse verströmt einen erfrischenden Zitronenduft und ist sowohl in der Küche als auch in der Heilkunde geschätzt.",
    history: "Schon im Mittelalter wurde Melisse in Klostergärten angebaut, um Herz und Gemüt zu stärken. Die Araber führten sie in die europäische Medizin ein, wo sie als Mittel gegen Melancholie und Schlaflosigkeit diente.",
    medApplication: "Melisse wirkt beruhigend bei Nervosität, Schlafproblemen und Magen-Darm-Beschwerden. Äußerlich angewendet kann sie bei Lippenherpes helfen.",
    tasteSmell: "Zitronig-frisch, mild süßlich, leicht herb.",
    preparationMethods: ['Tee', 'Tinktur', 'Bad', 'Öl'],
    combinations: ['kamille', 'lavendel', 'pfefferminze'],
    ingredients: [
      'Ätherische Öle (Citral, Citronellal)',
      'Rosmarinsäure',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Gärten', 'Kräuterbeete', 'sonnig bis halbschattig'],
    notesRisks: "In hohen Dosen kann es zu Schläfrigkeit kommen. Nicht während einer Schilddrüsenunterfunktion ohne ärztlichen Rat anwenden.",
    ads: []
  },
  {
    slug: 'thymian',
    title: 'Thymian',
    botanicalTitle: 'Thymus vulgaris',
    image: 'thymian.jpg',
    type: ['Kraut'],
    effectArea: ['antibakteriell', 'schleimlösend', 'entzündungshemmend', 'krampflösend'],
    teaser: "Thymian ist eine mediterrane Gewürz- und Heilpflanze mit intensivem Aroma und kleinen lila Blüten.",
    history: "Bereits die alten Ägypter nutzten Thymian zum Einbalsamieren, Römer schätzten ihn als Würzkraut und Heilpflanze. Im Mittelalter wurde er gegen Atemwegsbeschwerden eingesetzt.",
    medApplication: "Thymian lindert Husten und Bronchitis, fördert die Schleimlösung und wirkt desinfizierend im Mund- und Rachenraum.",
    tasteSmell: "Würzig, leicht pfeffrig, intensiv aromatisch mit harziger Note.",
    preparationMethods: ['Tee', 'Sirup', 'Öl', 'Inhalation'],
    combinations: ['salbei', 'pfefferminze', 'lavendel'],
    ingredients: [
      'Ätherische Öle (Thymol, Carvacrol)',
      'Flavonoide',
      'Gerbstoffe',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Kräuterbeete', 'Felsige Böden', 'sonnig'],
    notesRisks: "Nicht in zu hoher Dosierung bei empfindlichem Magen. Ätherisches Öl kann Haut reizen.",
    ads: []
  },
  {
    slug: 'salbei',
    title: 'Salbei',
    botanicalTitle: 'Salvia officinalis',
    image: 'salbei.jpg',
    type: ['Kraut'],
    effectArea: ['antibakteriell', 'entzündungshemmend', 'schweißhemmend', 'verdauungsfördernd'],
    teaser: "Salbei hat längliche, filzig behaarte aromatische Blätter. Die Pflanze wächst buschig und gedeiht sowohl wild als auch in Gärten.",
    history: "Salbei war bereits den Römern und Griechen als kostbares Heilkraut bekannt. Im Mittelalter wurde er zur „Königin der Heilpflanzen“ ernannt und war ein wichtiger Bestandteil der Klostermedizin. Salbei galt insbesondere als Mittel gegen Halsschmerzen und Entzündungen. In der Volksmedizin wurde er zudem als universelle Arznei und Würzkraut geschätzt.",
    medApplication: "Salbei wird als Tee oder Gurgellösung bei Halsentzündungen und Entzündungen der Mundschleimhaut verwendet. Seine antibakterielle Wirkung macht ihn zu einem bewährten Heilmittel bei Infekten. Außerdem ist Salbei hilfreich bei übermäßigem Schwitzen und kann äußerlich zur Wundheilung sowie als Badezusatz eingesetzt werden.",
    tasteSmell: "Herb, würzig, leicht bitter mit kampferartiger Note.",
    preparationMethods: ['Tee', 'Gurgellösung', 'Tinktur', 'Öl'],
    combinations: ['thymian', 'kamille', 'rosmarin'],
    ingredients: [
      'Ätherische Öle (Thujon, Cineol)',
      'Gerbstoffe',
      'Flavonoide',
      'Bitterstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Kräuterbeete', 'Steinige Böden', 'sonnig'],
    notesRisks: "Nicht in großen Mengen in der Schwangerschaft. Längere Anwendung von reinem Öl vermeiden.",
    ads: []
  },
  {
    slug: 'rosmarin',
    title: 'Rosmarin',
    botanicalTitle: 'Rosmarinus officinalis',
    image: 'rosmarin.jpg',
    type: ['Kraut'],
    effectArea: ['durchblutungsfördernd', 'verdauungsfördernd', 'belebend', 'antioxidativ'],
    teaser: "Rosmarin ist ein immergrüner Halbstrauch mit kräftigem Aroma, der aus dem Mittelmeerraum stammt.",
    history: "Schon die Griechen und Römer nutzten Rosmarin als Gedächtnisstütze und Schutzpflanze. In der Küche und Medizin gleichermaßen beliebt.",
    medApplication: "Wirkt anregend, fördert die Verdauung und lindert Muskelschmerzen. Äußerlich als Badezusatz belebend.",
    tasteSmell: "Kräftig harzig, leicht kampferartig, würzig.",
    preparationMethods: ['Tee', 'Öl', 'Bad', 'Tinktur'],
    combinations: ['salbei', 'thymian', 'lavendel'],
    ingredients: [
      'Ätherische Öle (1,8-Cineol, Campher)',
      'Bitterstoffe',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [5, 6, 7],
    locations: ['sonnige Kräuterbeete', 'trockene Böden', 'Mittelmeerregion'],
    notesRisks: "Nicht bei Bluthochdruck oder in der Schwangerschaft in großen Mengen verwenden.",
    ads: []
  },
  {
    slug: 'brennnessel',
    title: 'Brennnessel',
    botanicalTitle: 'Urtica dioica',
    image: 'brennnessel.jpg',
    type: ['Kraut'],
    effectArea: ['stoffwechselanregend', 'entwässernd', 'entzündungshemmend', 'blutreinigend'],
    teaser: 'Vom "Unkraut" zum Superfood: Die Brennnessel ist Deutschlands unterschätzteste Heilpflanze. Reich an Vitaminen, natürlicher Entzündungshemmer und nachhaltiger Rohstoff - entdecken Sie das grüne Multitalent vor Ihrer Haustür!',
    history: 'Die Brennnessel zählt zu den ältesten Kulturbegleitern der Menschheit und ist seit Jahrtausenden in Europa, Asien und Nordamerika heimisch. Bereits in der Bronzezeit nutzte man Brennnesselfasern zur Textilherstellung - lange vor der Einführung von Flachs und Hanf. Die alten Germanen verehrten sie als heilige Pflanze des Donnergottes Thor und glaubten, sie schütze vor Blitzschlag. Römische Soldaten rieben sich mit Brennnesseln ein, um bei kaltem Wetter warm zu bleiben - eine Praxis namens "Urtifikation". Im Mittelalter war sie als "Allheilmittel der armen Leute" bekannt, da sie überall wuchs und vielseitig verwendbar war. Hildegard von Bingen empfahl sie gegen Vergesslichkeit und bei Magenleiden. In der Volksmedizin galt sie als Frühjahrs-Entgiftungskur. Während der beiden Weltkriege erlebte die Brennnessel eine Renaissance als Ersatz für importierte Fasern und Nahrungsmittel. Heute wird sie wieder als nachhaltige Ressource für Textilien, Kosmetika und als "Superfood" wiederentdeckt.',
    medApplication: 'Die Brennnessel ist ein wahres Multitalent in der Naturheilkunde und Ernährung. Als Heilpflanze wirkt sie harntreibend und wird bei Blasen- und Nierenleiden sowie zur Durchspülungstherapie bei Harnwegsinfekten eingesetzt. Die entzündungshemmenden Eigenschaften helfen bei rheumatischen Beschwerden und Arthritis - sowohl innerlich als Tee oder Extrakt als auch äußerlich durch das traditionelle "Brennen" mit frischen Pflanzen. In der Dermatologie lindert Brennnessel Ekzeme, Akne und Schuppen, während sie das Haarwachstum anregt und gegen Haarausfall wirkt. Als Nahrungsmittel ist sie reich an Eisen, Vitamin C, Kalium und Protein - die jungen Blätter werden wie Spinat zubereitet oder zu grünen Smoothies verarbeitet. In der Landwirtschaft dient sie als natürlicher Dünger und Schädlingsbekämpfung. Die Fasern werden zu nachhaltigen Textilien verarbeitet. Modern wird Brennnessel auch bei Allergien, zur Blutreinigung und als natürliches Antihistaminikum geschätzt. Vorsicht ist bei Herz- und Nierenerkrankungen geboten.',
    tasteSmell: "Spinatähnlich, leicht nussig, grün-aromatisch.",
    preparationMethods: ['Tee', 'Gemüse', 'Tinktur'],
    combinations: ['schachtelhalm', 'löwenzahn', 'petersilie'],
    ingredients: [
      'Mineralstoffe (Eisen, Kalzium, Magnesium, Kalium)',
      'Vitamine (A, C, K)',
      'Flavonoide',
      'Chlorophyll',
      'Kieselsäure'
    ],
    harvestMonths: [4, 5, 6],
    locations: ['Wegränder', 'Wiesen', 'nährstoffreiche Böden'],
    notesRisks: "Frische Pflanze kann Hautreizungen verursachen. Nicht bei Herz- oder Nierenproblemen in großen Mengen verzehren.",
    ads: []
  },
  {
    slug: 'schafgarbe',
    title: 'Schafgarbe',
    botanicalTitle: 'Achillea millefolium',
    image: 'schafgarbe.jpg',
    type: ['Kraut', 'Blüte'],
    effectArea: ['krampflösend', 'entzündungshemmend', 'blutstillend', 'verdauungsfördernd'],
    teaser: "Schafgarbe mit ihren gefiederten Blättern und weißen Blüten ist ein bewährtes Heilkraut.",
    history: "Schon in der Antike bekannt, wird sie seit Jahrhunderten gegen Verdauungsbeschwerden und Wunden eingesetzt.",
    medApplication: "Hilft bei Magen-Darm-Krämpfen, reguliert den Menstruationszyklus und unterstützt die Wundheilung.",
    tasteSmell: "Herb, leicht bitter, aromatisch.",
    preparationMethods: ['Tee', 'Tinktur', 'Bad'],
    combinations: ['kamille', 'pfefferminze', 'melisse'],
    ingredients: [
      'Ätherische Öle (Chamazulen, Cineol)',
      'Bitterstoffe',
      'Flavonoide',
      'Gerbstoffe'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Wiesen', 'Wegränder', 'sonnige Hänge'],
    notesRisks: "Kann Hautreizungen verursachen. Nicht in der Schwangerschaft anwenden.",
    ads: []
  },
  {
    slug: 'ringelblume',
    title: 'Ringelblume',
    botanicalTitle: 'Calendula officinalis',
    image: 'ringelblume.jpg',
    type: ['Blüte'],
    effectArea: ['entzündungshemmend', 'wundheilend', 'antibakteriell', 'hautpflegend'],
    teaser: "Leuchtend orange Blüten machen die Ringelblume zu einem Blickfang im Garten.",
    history: "Seit dem Mittelalter bekannt als Heil- und Zierpflanze. Vor allem in Salben und Tees verwendet.",
    medApplication: "Fördert die Wundheilung, lindert Hautreizungen und wirkt entzündungshemmend.",
    tasteSmell: "Mild, leicht würzig, blumig.",
    preparationMethods: ['Tee', 'Salbe', 'Tinktur'],
    combinations: ['kamille', 'schafgarbe', 'lavendel'],
    ingredients: [
      'Flavonoide',
      'Carotinoide',
      'Saponine',
      'Ätherische Öle'
    ],
    harvestMonths: [6, 7, 8],
    locations: ['Gärten', 'Beete', 'sonnig'],
    notesRisks: "Kann bei Allergien gegen Korbblütler problematisch sein.",
    ads: []
  },
  {
    slug: 'baldrian',
    title: 'Baldrian',
    botanicalTitle: 'Valeriana officinalis',
    image: 'baldrian.jpg',
    type: ['Wurzel'],
    effectArea: ['beruhigend', 'schlaffördernd', 'krampflösend'],
    teaser: 'Seit 2000 Jahren vertrauen Menschen auf Baldrian als natürlichen Schlafbringer. Das "Katzenkraut" beruhigt Nerven, fördert erholsamen Schlaf und macht nicht abhängig - Natur pur gegen moderne Unruhe!',
    history: 'Baldrian gehört zu den ältesten Heilpflanzen der Menschheit mit über 2000-jähriger dokumentierter Geschichte. Bereits die antiken Griechen kannten seine Wirkung - Hippokrates beschrieb ihn als harntreibendes Mittel, während Dioskurides ihn in seinem Werk "De Materia Medica" erwähnte. Die Römer gaben ihm den Namen "Valeriana", abgeleitet vom lateinischen "valere" (gesund sein). Im Mittelalter war Baldrian fester Bestandteil der Klostermedizin, Hildegard von Bingen empfahl ihn gegen Seitenschmerzen und als Schlafmittel. Renaissance-Ärzte wie Paracelsus schätzten ihn als eines der besten Beruhigungsmittel gegen Nervenleiden und "Hysterie". Der volkstümliche Name "Katzenkraut" entstand, weil Katzen magisch vom intensiven Wurzelgeruch angezogen werden. Im 19. Jahrhundert wurden die ersten Wirkstoffe isoliert, heute ist Baldrian wissenschaftlich als natürliches Beruhigungs- und Schlafmittel anerkannt.',
    medApplication: 'Baldrian wird hauptsächlich als natürliches Beruhigungs- und Schlafmittel eingesetzt. Die Baldrianwurzel hilft bei Ein- und Durchschlafstörungen, ohne dabei abhängig zu machen oder einen "Kater-Effekt" am nächsten Tag zu verursachen. Bei nervöser Unruhe, Stress und innerer Anspannung wirkt er entspannend auf das zentrale Nervensystem. Traditionell wird Baldrian auch bei Angststörungen, Prüfungsangst und nervösen Herzbeschwerden verwendet. In der Frauenheilkunde findet er Anwendung bei menstruationsbedingten Beschwerden und Wechseljahresbeschwerden. Äußerlich als Bad angewendet, kann Baldrian bei Muskelverspannungen und nervösen Hautreizungen lindernd wirken. Die Darreichungsformen reichen von Tees und Tinkturen über Tabletten bis zu ätherischen Ölen. Wichtig ist eine regelmäßige Einnahme über mehrere Wochen, da die volle Wirkung erst nach einiger Zeit eintritt. Bei schweren Schlafstörungen sollte immer ein Arzt konsultiert werden.',
    tasteSmell: "Erdig, aromatisch, leicht bitter mit charakteristischem Geruch.",
    preparationMethods: ['Tee', 'Tinktur', 'Tablette'],
    combinations: ['melisse', 'hopfen', 'passionsblume'],
    ingredients: [
      'Valepotriate',
      'Ätherische Öle',
      'Alkaloide',
      'Flavonoide'
    ],
    harvestMonths: [9, 10],
    locations: ['Feuchtwiesen', 'Waldränder', 'Gärten'],
    notesRisks: "Längere Anwendung kann zu Tagesmüdigkeit führen. Nicht mit Alkohol kombinieren.",
    ads: []
  },
  {
      slug: 'cistus',
      title: 'Cistus',
      botanicalTitle: 'Cistus incanus',
      image: 'cistus.jpg',
      type: ['Blatt'],
      effectArea: ['antiviral', 'antibakteriell', 'antioxidativ', 'entzündungshemmend'],
      teaser: 'Die Zistrose - Griechenlands Immunbooster aus der Antike! Reich an Polyphenolen, stärkt natürlich die Abwehrkräfte und schützt vor Infekten. Das mediterrane Heilkraut erobert moderne Hausapotheken.',
      history: 'Die Zistrose stammt aus dem Mittelmeerraum und ist seit der Antike als Heilpflanze bekannt. Bereits im alten Griechenland schätzten Ärzte wie Dioskurides ihre heilenden Eigenschaften. Das aus den Blättern gewonnene Labdanum-Harz galt als kostbares Räucherwerk und wurde in religiösen Zeremonien verwendet. Die Griechen nannten sie "Ladanon" und nutzten sie gegen Durchfall und Wunden. Im Mittelalter geriet Cistus in Europa weitgehend in Vergessenheit, blieb aber in der Volksmedizin Griechenlands und der Türkei lebendig. Dort tranken die Menschen traditionell Zistrosen-Tee zur Stärkung der Gesundheit und bei Erkältungen. Die Hirten sammelten das klebrige Harz von den Ziegen, die durch Cistus-Büsche gelaufen waren - ein mühsamer aber lukrativer Prozess. In der modernen Phytotherapie wurde Cistus erst in den 1990er Jahren wiederentdeckt, als Forscher ihre außergewöhnlich hohe Konzentration an Polyphenolen erkannten. Heute gilt sie als eine der polyphenolreichsten Pflanzen Europas und erlebt eine Renaissance als natürliches Immunstärkungsmittel.',
      medApplication: 'Cistus incanus ist vor allem für ihre immunstärkenden und antiviralen Eigenschaften bekannt. Der hohe Gehalt an Polyphenolen macht sie zu einem natürlichen Schutzschild gegen Erkältungen, Grippe und andere Virusinfekte. Als Tee getrunken, kann sie präventiv das Immunsystem stärken oder bei akuten Infekten die Heilung beschleunigen. Die antioxidative Wirkung schützt Zellen vor freien Radikalen und verlangsamt Alterungsprozesse. In der Dermatologie wird Cistus bei Hautproblemen wie Neurodermitis, Akne und Ekzemen eingesetzt - sowohl innerlich als auch äußerlich als Waschung oder Kompresse. Die antibakteriellen Eigenschaften helfen bei Wunden und Entzündungen im Mund- und Rachenraum. Cistus unterstützt auch die Darmgesundheit und kann bei Durchfall regulierend wirken. In der Anti-Aging-Medizin wird sie wegen ihrer zellschützenden Eigenschaften geschätzt. Studien zeigen positive Effekte bei Borreliose-Nachbehandlung und als Unterstützung bei Schwermetallausleitung. Die Anwendung erfolgt meist als Tee, Extrakt oder Mundspülung. Besonders in der Erkältungssaison hat sich die regelmäßige Einnahme von Cistus-Tee bewährt.',
      tasteSmell: "Herb, leicht bitter, harzig.",
      preparationMethods: ['Tee', 'Tinktur'],
      combinations: ['salbei', 'thymian', 'kamille'],
      ingredients: [
        'Polyphenole',
        'Flavonoide',
        'Ätherische Öle',
        'Gerbstoffe'
      ],
      harvestMonths: [5, 6, 7],
      locations: ['Mittelmeerregion', 'sonnig', 'trockene Hänge'],
      notesRisks: 'Cistus gilt als sehr gut verträglich, dennoch sollten Schwangere und Stillende auf die Einnahme verzichten. Bei Eisenmangel ist Vorsicht geboten, da Polyphenole die Eisenaufnahme hemmen können. Seltene allergische Reaktionen sind möglich.',
      ads: []
  },
  {
      slug: 'frauenmantel',
      title: 'Frauenmantel',
      botanicalTitle: 'Alchemilla vulgaris',
      image: 'frauenmantel.jpg',
      type: ['Blatt'],
      effectArea: ['hormonregulierend', 'krampflösend', 'entzündungshemmend'],
      teaser: 'In der Frühschwangerschaft sollte Frauenmantel gemieden werden, da er wehenfördernd wirken kann. Bei Hormonstörungen ärztlichen Rat einholen. Nebenwirkungen sind selten, gelegentlich Magenbeschwerden möglich.',
  history: 'Der Frauenmantel ist in den Bergregionen Europas heimisch und trägt seinen Namen aufgrund der charakteristischen, mantelförmigen Blätter. Bereits im Mittelalter galt er als wichtigste Heilpflanze für Frauenleiden und wurde in Klostergärten kultiviert. Hildegard von Bingen lobte ihn als "Frauenhilfe" bei Menstruationsbeschwerden und Geburten. Der wissenschaftliche Name "Alchemilla" stammt aus der Alchemie - die Alchemisten sammelten den Tau aus den gefalteten Blättern für ihre Experimente, da sie ihm magische Kräfte zuschrieben. In der Volksmedizin hieß er auch "Marienkraut" oder "Tauschüsselchen" wegen der charakteristischen Tautropfen. Kräuterfrauen des Mittelalters verwendeten ihn bei schweren Geburten und zur Wundheilung. In alpinen Regionen war er fester Bestandteil der Hausapotheke jeder Familie. Die Germanen weihten ihn der Göttin Freya und glaubten an seine schützenden Eigenschaften für Mutter und Kind. Paracelsus empfahl ihn als "Allheilmittel für die Frauen". Heute wird Frauenmantel wissenschaftlich erforscht und seine traditionelle Verwendung durch moderne Studien bestätigt.',
  medApplication: 'Frauenmantel ist die klassische Heilpflanze für alle Phasen des weiblichen Lebens. Bei Menstruationsbeschwerden reguliert er den Zyklus, lindert Krämpfe und reduziert zu starke Blutungen durch seine zusammenziehenden Gerbstoffe. In der Schwangerschaft kann er ab dem zweiten Trimester zur Geburtsvorbereitung eingesetzt werden und soll Wehen regulieren. Nach der Geburt fördert er die Rückbildung und unterstützt die Wundheilung. In den Wechseljahren mildert er hormonelle Schwankungen und damit verbundene Beschwerden wie Hitzewallungen. Auch bei Weißfluss und anderen gynäkologischen Problemen wird er traditionell verwendet. Äußerlich angewendet heilt Frauenmantel Wunden, lindert Hautirritationen und strafft das Gewebe - daher wird er auch in der Naturkosmetik geschätzt. Bei Magen-Darm-Problemen wirkt er beruhigend und entzündungshemmend. Die Anwendung erfolgt meist als Tee, Sitzbad oder Waschung. Männer nutzen ihn bei Durchfall und zur Wundheilung. Modern wird Frauenmantel auch bei Kinderwunsch zur Zyklusregulierung und Fruchtbarkeitsförderung empfohlen. Die Heilwirkung beruht hauptsächlich auf Gerbstoffen, Flavonoiden und Saponinen.',
tasteSmell: "Mild, leicht herb.",
      preparationMethods: ['Tee', 'Tinktur'],
      combinations: ['schafgarbe', 'kamille', 'melisse'],
      ingredients: [
        'Gerbstoffe',
        'Flavonoide',
        'Bitterstoffe',
        'Saponine'
      ],
      harvestMonths: [5, 6, 7, 8],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: 'In der Frühschwangerschaft sollte Frauenmantel gemieden werden, da er wehenfördernd wirken kann. Bei Hormonstörungen ärztlichen Rat einholen. Nebenwirkungen sind selten, gelegentlich Magenbeschwerden möglich.',
      ads: []
  },
  {
      slug: 'giersch',
      title: 'Giersch',
      botanicalTitle: 'Aegopodium podagraria',
      image: 'giersch.jpg',
      type: ['Blatt'],
      effectArea: ['entwässernd', 'stoffwechselanregend', 'entzündungshemmend'],
      teaser: "Vom Gartenfeind zum Superfood: Giersch ist das unterschätzte Wildkraut vor der Haustür! Reich an Vitamin C, hilft bei Gicht und Rheuma. Wenn du ihn nicht besiegen kannst, ess ihn einfach auf!",
      history: 'Giersch ist seit Jahrtausenden in Europa heimisch und begleitet die menschliche Zivilisation als Kultur- und Ruderalpflanze. Bereits die Römer kannten ihn als "Herba Gerardi" und nutzten ihn sowohl als Nahrung als auch als Heilmittel gegen Gicht - daher auch der lateinische Name "podagraria" (Gichtfuß). Im Mittelalter war Giersch ein wichtiges Gemüse und Heilkraut in Klostergärten. Mönche kultivierten ihn gezielt und verbreiteten ihn in ganz Europa. Der deutsche Name leitet sich von "gier" (begierig) ab, was auf sein schnelles, unaufhaltsames Wachstum anspielt. Hildegard von Bingen empfahl ihn gegen Rheuma und Verdauungsprobleme. In der Volksmedizin hieß er auch "Ziegenfuß" wegen seiner geteilten Blattform oder "Geißfuß". Während der beiden Weltkriege erlebte Giersch eine Renaissance als Notnahrung und Vitaminspender. Paracelsus schätzte ihn als harntreibendes Mittel. In der traditionellen Kräuterheilkunde galt er als "Gichtmittel der armen Leute". Heute wird das vermeintliche "Unkraut" als regionales Superfood und nachhaltiges Wildgemüse wiederentdeckt, während Gärtner noch immer seinen Ausbreitungsdrang fürchten.',
      medApplication: 'Giersch ist sowohl als Heilpflanze als auch als nährstoffreiches Wildgemüse wertvoll. Medizinisch wird er hauptsächlich bei rheumatischen Beschwerden, Gicht und Arthritis eingesetzt - seine entzündungshemmenden und harnsäuresenkenden Eigenschaften machen ihn zum natürlichen Gichtmittel. Die harntreibende Wirkung unterstützt bei Blasen- und Nierenerkrankungen sowie zur Entgiftung. Als Nahrungsmittel übertrifft Giersch viele Kulturgemüse: Er enthält mehr Vitamin C als Zitrusfrüchte, reichlich Kalium, Eisen und Karotin. Die jungen Blätter schmecken wie eine Mischung aus Petersilie und Sellerie und eignen sich für Salate, Suppen, Pestos und Smoothies. Äußerlich angewendet lindert Giersch Insektenstiche, kleinere Wunden und Hautirritationen. In der Frühjahrskur wirkt er blutreinigend und stoffwechselanregend. Seine antioxidativen Eigenschaften schützen vor freien Radikalen. Giersch unterstützt auch die Verdauung und kann bei Darmträgheit helfen. In der Naturkosmetik wird er für straffende Gesichtsmasken verwendet. Die Samen können als Gewürz genutzt werden. Wichtig: Nur eindeutig identifizierten Giersch sammeln, da Verwechslungsgefahr mit giftigen Doldenblütlern besteht.',
      tasteSmell: "Frisch, mild, leicht nach Petersilie.",
      preparationMethods: ['Salat', 'Pesto', 'Tee'],
      combinations: ['brennnessel', 'löwenzahn', 'petersilie'],
      ingredients: [
        'Vitamin C',
        'Kalium',
        'Flavonoide',
        'Ätherische Öle'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Gärten', 'Wälder', 'Wegränder'],
      notesRisks: "Größte Gefahr ist die Verwechslung mit giftigen Doldenblütlern wie Schierling. Nur sammeln bei absoluter Sicherheit! Bei Nierensteinen wegen harntreibender Wirkung ärztlich abklären. Selten allergische Reaktionen möglich.",
      ads: []
  },
  {
      slug: 'ingwer',
      title: 'Ingwer',
      botanicalTitle: 'Zingiber officinale',
      image: 'ingwer.jpg',
      type: ['Wurzel'],
      effectArea: ['entzündungshemmend', 'verdauungsfördernd', 'durchblutungsfördernd', 'immunsystemstärkend'],
      teaser: "Ingwer - die scharfe Wunderknolle aus Asien! Bekämpft Übelkeit, stärkt dein Immunsystem und heizt deinem Stoffwechsel ordentlich ein. Entdecke, warum diese Wurzel seit 5000 Jahren als Heilmittel verehrt wird!",
      history: 'Ingwer stammt ursprünglich aus Südostasien und wird seit über 5000 Jahren kultiviert. In China und Indien galt er schon früh als universelles Heilmittel - Konfuzius soll täglich Ingwer gegessen haben. Die alten Inder betrachteten ihn als "Vishwabhesaj" - universelle Medizin - und nutzen ihn bis heute in der Ayurveda-Lehre. Über die Seidenstraße gelangte Ingwer nach Europa, wo er im Mittelalter zu den kostbarsten Gewürzen zählte. Marco Polo beschrieb seine Verwendung am chinesischen Kaiserhof. Die Araber handelten jahrhundertelang mit der wertvollen Knolle und hüteten das Geheimnis ihrer Herkunft. Im alten Rom war Ingwer so teuer, dass er mit Gold aufgewogen wurde. Seefahrer der Antike nutzten ihn gegen Seekrankheit - eine Tradition, die bis heute anhält. Die alten Griechen wickelten ihn in Brot ein, was zur Erfindung des Lebkuchens führte. Im 16. Jahrhundert brachten portugiesische Händler Ingwer nach Westafrika und in die Karibik. Heute ist er weltweit verbreitet und erlebt als "Superfood" eine Renaissance in der westlichen Welt, wo seine jahrtausendealten Heilkräfte neu geschätzt werden.',
      medApplication: 'Ingwer ist ein wahres Multitalent für deine Gesundheit. Am bekanntesten ist seine Wirkung gegen Übelkeit - ob bei Reisekrankheit, Schwangerschaftsübelkeit oder Chemotherapie. Die scharfen Gingerole regen die Verdauung an und beruhigen den Magen. Als natürlicher Entzündungshemmer hilft Ingwer bei Rheuma, Arthritis und Muskelschmerzen. Seine immunstärkenden Eigenschaften machen ihn zum idealen Begleiter in der Erkältungszeit - Ingwertee mit Zitrone und Honig ist ein bewährtes Hausmittel. Die durchblutungsfördernde Wirkung wärmt von innen und kann bei Migräne Linderung bringen. Ingwer kurbelt den Stoffwechsel an und unterstützt beim Abnehmen. In der Küche verleiht er Gerichten nicht nur Schärfe, sondern macht fette Speisen bekömmlicher. Als Tee, in Smoothies oder kandiert genossen, stärkt er deine Abwehrkräfte. Äußerlich angewendet als Wickel oder Kompresse lindert er Verspannungen. Studien zeigen positive Effekte bei Diabetes und Herz-Kreislauf-Erkrankungen. Auch bei Menstruationsbeschwerden kann Ingwer helfen. Du kannst ihn frisch, getrocknet, als Pulver oder Öl verwenden - je nach Anwendungszweck.',
      tasteSmell: "Scharf, zitronig, aromatisch.",
      preparationMethods: ['Tee', 'Pulver', 'Frischverwendung', 'Tinktur'],
      combinations: ['zitronengras', 'kurkuma', 'honig'],
      ingredients: [
        'Gingerole',
        'Shogaole',
        'Ätherische Öle',
        'Vitamin C'
      ],
      harvestMonths: [1, 2, 11, 12],
      locations: ['Tropen', 'Gewächshaus', 'Kübelkultur'],
      notesRisks: "Bei Gallensteinen solltest du auf Ingwer verzichten. Vor Operationen absetzen, da er die Blutgerinnung beeinflusst. In hohen Dosen kann er Sodbrennen verstärken. Bei Blutverdünnern ärztlich abklären.",
      ads: []
  },
  {
      slug: 'johanniskraut',
      title: 'Johanniskraut',
      botanicalTitle: 'Hypericum perforatum',
      image: 'johanniskraut.jpg',
      type: ['Blüte'],
      effectArea: ['stimmungsaufhellend', 'antidepressiv', 'entzündungshemmend'],
      teaser: "Johanniskraut ist an seinen leuchtend gelben Blüten und durchscheinenden Blättern zu erkennen – es wächst auf Wiesen und an Wegrändern.",
      history: "Johanniskraut wird seit Jahrhunderten traditionell bei Verstimmungen und zur Wundbehandlung eingesetzt. Seine gelben Blüten gelten als „Sonnenfänger“ und Symbol für Licht und Hoffnung. Die Entdeckung der stimmungsaufhellenden Wirkung trug zu seiner heutigen Bedeutung als pflanzliches Antidepressivum maßgeblich bei. In Volksmedizin und Kräuterheilkunde ist Johanniskraut fest verwurzelt.",
      medApplication: "Johanniskraut hilft natürlich bei leichten bis mittleren Depressionen und nervösem Unwohlsein. Es wird als Tee, Öl oder Extrakt angewendet und ist gut verträglich. Darüber hinaus kommen seine entzündungshemmenden Eigenschaften bei Hautproblemen und leichten Verbrennungen äußerlich zum Einsatz.",
      tasteSmell: "Herb, leicht bitter, aromatisch.",
      preparationMethods: ['Tee', 'Ölauszug', 'Tinktur'],
      combinations: ['melisse', 'baldrian', 'passionsblume'],
      ingredients: [
        'Hypericin',
        'Hyperforin',
        'Flavonoide',
        'Gerbstoffe'
      ],
      harvestMonths: [6, 7, 8],
      locations: ['Wiesen', 'Waldränder', 'sonnige Hänge'],
      notesRisks: "Erhöht die Lichtempfindlichkeit der Haut; kann Wechselwirkungen mit Medikamenten verursachen.",
      ads: []
  },
  {
      slug: 'loewenzahn',
      title: 'Löwenzahn',
      botanicalTitle: 'Taraxacum officinale',
      image: 'loewenzahn.jpg',
      type: ['Blatt', 'Wurzel', 'Blüte'],
      effectArea: ['entwässernd', 'verdauungsfördernd', 'stoffwechselanregend'],
      teaser: "Löwenzahn mit seinen leuchtend gelben Blüten ist ein Symbol des Frühlings. Doch er ist nicht nur schön – seine Heilwirkung ist vielseitig und tiefgehend.",
      history: "Löwenzahn wurde bereits im Altertum als verdauungsförderndes Mittel verwendet. Im Mittelalter galt er als 'Lebenselixier' für Leber und Galle. Seine Nutzung reicht von der Volksmedizin bis zur modernen Phytotherapie.",
      medApplication: "Löwenzahn regt Leber, Galle und Nieren an und unterstützt den Körper bei der Entgiftung. Er wird bei Völlegefühl, Blähungen und Appetitlosigkeit empfohlen. Besonders wirksam sind Tees und Tinkturen aus Wurzel und Blatt.",
      tasteSmell: "Bitter, leicht nussig, frisch.",
      preparationMethods: ['Tee', 'Salat', 'Kaffeeersatz'],
      combinations: ['brennnessel', 'giersch', 'petersilie'],
      ingredients: [
        'Bitterstoffe',
        'Flavonoide',
        'Vitamin C',
        'Kalium'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: "Kann bei Gallensteinen problematisch sein.",
      ads: []
  },
  {
      slug: 'maedesuess',
      title: 'Mädesüß',
      botanicalTitle: 'Filipendula ulmaria',
      image: 'maedesuess.webp',
      type: ['Blüte'],
      effectArea: ['schmerzstillend', 'entzündungshemmend', 'fiebersenkend'],
      teaser: "Mädesüß - das natürliche Aspirin aus der Wiese! Diese duftende Heilpflanze lindert Schmerzen, senkt Fieber und bekämpft Entzündungen. Entdecke die sanfte Alternative zu synthetischen Schmerzmitteln!",
      history: 'Mädesüß ist in Europa heimisch und wächst an feuchten Standorten wie Bachufern und Wiesen. Bereits die Kelten und Germanen schätzten die Pflanze als heilig und verwendeten sie bei Ritualen und als Schmerzmittel. Der Name "Mädesüß" leitet sich vom mittelhochdeutschen "met" (Met) ab, da die Blüten traditionell zur Aromatisierung des Honigweins verwendet wurden. Im Mittelalter war Mädesüß eine der wichtigsten Heilpflanzen für Fieber und Schmerzen. Die Druiden verehrten es als eine der drei heiligsten Pflanzen neben Eisenkraut und Wasserminze. In England hieß es "Queen of the Meadow" und wurde in Schlafzimmern ausgestreut, um einen süßen Duft zu verbreiten. 1838 gelang dem italienischen Chemiker Raffaele Piria die Isolierung der Salicylsäure aus Mädesüß - der Grundstoff für Aspirin war entdeckt. Der Markenname "Aspirin" leitet sich sogar vom alten botanischen Namen "Spiraea" ab. Pfarrer Kneipp empfahl Mädesüß als "Aspirin der Wiese" bei Rheuma und Kopfschmerzen. Heute erlebt die Pflanze als natürliche Alternative zu synthetischen Schmerzmitteln eine Renaissance und wird in der Phytotherapie wieder geschätzt.',
      medApplication: 'Mädesüß ist das pflanzliche Aspirin und wird hauptsächlich als natürliches Schmerzmittel eingesetzt. Die enthaltene Salicylsäure wirkt schmerzlindernd, fiebersenkend und entzündungshemmend - ideal bei Kopfschmerzen, Rheuma und grippalen Infekten. Anders als synthetisches Aspirin ist Mädesüß magenschonend, da es zusätzliche Gerbstoffe enthält, die den Magen schützen. Bei Erkältungen und Fieber kannst du Mädesüßtee trinken, der nicht nur die Symptome lindert, sondern auch angenehm süßlich schmeckt. Die harntreibende Wirkung unterstützt bei Blasenentzündungen und Nierenproblemen. In der Rheumabehandlung wird Mädesüß sowohl innerlich als auch äußerlich als Umschlag angewendet. Die Blüten enthalten ätherische Öle, die krampflösend wirken und bei Magen-Darm-Beschwerden helfen. Auch bei Sodbrennen kann Mädesüß paradoxerweise Linderung bringen, obwohl es Salicylsäure enthält. Als Tee, Tinktur oder in Salben verarbeitet, bietet es vielseitige Anwendungsmöglichkeiten. In der Aromatherapie werden die Blüten wegen ihres mandelartigen Dufts geschätzt. Modern wird Mädesüß auch bei Cellulite und zur Hautstraffung in der Naturkosmetik verwendet.',
      tasteSmell: "Süßlich, mandelartig, aromatisch.",
      preparationMethods: ['Tee', 'Tinktur', 'Sirup'],
      combinations: ['weidenrinde', 'lindenblüte', 'holunder'],
      ingredients: [
        'Salicylsäureverbindungen',
        'Flavonoide',
        'Gerbstoffe',
        'Ätherische Öle'
      ],
      harvestMonths: [6, 7, 8],
      locations: ['Feuchtwiesen', 'Bachufer', 'Gräben'],
      notesRisks: "Bei Salicylat-Allergie oder Aspirin-Unverträglichkeit solltest du Mädesüß meiden. Nicht mit Blutverdünnern kombinieren. In der Schwangerschaft und Stillzeit nur nach Rücksprache verwenden.",
      ads: []
  },
  {
      slug: 'spitzwegerich',
      title: 'Spitzwegerich',
      botanicalTitle: 'Plantago lanceolata',
      image: 'spitzwegerich.jpg',
      type: ['Blatt'],
      effectArea: ['hustenstillend', 'entzündungshemmend', 'wundheilend'],
      teaser: "Spitzwegerich ist eine robuste Pflanze mit langen, schmalen Blättern. Er wächst oft unbeachtet an Wegrändern – dabei steckt in ihm eine wahre Heilkraft.",
      history: "Bereits in der Antike war Spitzwegerich bekannt. Die Germanen und später die Klostermedizin nutzten ihn zur Behandlung von Husten, Insektenstichen und Hautverletzungen. Besonders beliebt war er wegen seiner reizlindernden Schleimstoffe.",
      medApplication: "Spitzwegerich lindert Hustenreiz, unterstützt die Schleimlösung und wirkt bei Reizungen der Atemwege. Als Tee, Sirup oder Tinktur wird er vor allem bei Bronchitis und Reizhusten verwendet. Äußerlich hilft er bei kleinen Wunden und Insektenstichen.",
      tasteSmell: "Mild, leicht herb, grasig.",
      preparationMethods: ['Tee', 'Sirup', 'Frischsaft'],
      combinations: ['thymian', 'kamille', 'islandmoos'],
      ingredients: [
        'Schleimstoffe',
        'Gerbstoffe',
        'Aucubin',
        'Flavonoide'
      ],
      harvestMonths: [4, 5, 6, 7, 8, 9],
      locations: ['Wiesen', 'Wegränder', 'Gärten'],
      notesRisks: "Keine bekannten Nebenwirkungen bei normaler Anwendung.",
      ads: []
  },
  {
      slug: 'vogelmiere',
      title: 'Vogelmiere',
      botanicalTitle: 'Stellaria media',
      image: 'vogelmiere.jpg',
      type: ['Blatt', 'Stängel', 'Blüte'],
      effectArea: ['hautheilend', 'entzündungshemmend', 'stoffwechselanregend'],
      teaser: "Vogelmiere ist eine zarte, bodennahe Pflanze mit kleinen weißen Blüten. Sie wächst das ganze Jahr über – oft übersehen, aber voller Kraft.",
      history: "Seit Jahrhunderten wird Vogelmiere in der Volksmedizin verwendet – vor allem zur Hautpflege und bei Ekzemen. Ihre milden Eigenschaften machten sie besonders bei empfindlicher Haut beliebt.",
      medApplication: "Vogelmiere wirkt kühlend und juckreizstillend bei Hautproblemen wie Ekzemen oder Insektenstichen. Sie wird frisch als Auflage, in Salben oder als Tee bei Stoffwechselstörungen verwendet.",
      tasteSmell: "Mild, frisch, leicht süßlich.",
      preparationMethods: ['Salat', 'Smoothie', 'Tee'],
      combinations: ['giersch', 'brennnessel', 'löwenzahn'],
      ingredients: [
        'Vitamin C',
        'Saponine',
        'Mineralstoffe',
        'Flavonoide'
      ],
      harvestMonths: [3, 4, 5, 6, 7, 8, 9, 10],
      locations: ['Gärten', 'Wiesen', 'Beete'],
      notesRisks: "Kann bei übermäßigem Verzehr leicht abführend wirken.",
      ads: []
  }



]
